---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "polysolver"
channels:
  - conda-forge
  - bioconda
  - defaults
  - compbiocore
dependencies:
  - "compbiocore::hla-polysolver=1.0.0"
